data-path = "QBFT-Network/Node-1/data" # Path data directory

bootnodes = ["enode://5415463e0773a7f6d9047156127f756de1f168c18e42632f4b84c1e1cdba16319f030558b7426dae2b74ab1716faa335ccf8ef40e81747f393e1b970e5d542ce@45.93.136.167:30303"]

p2p-port = 30303
max-peers = 42

rpc-http-host = "127.0.0.1"
rpc-http-port = 8545
rpc-http-api = ["ETH,NET,QBFT,TRACE"]
rpc-http-apis = ["ETH,NET,QBFT,TRACE"]

genesis-file = "QBFT-Network/genesis.json" # Path to the custom genesis file

p2p-enabled = true
logging = "INFO"
color-enabled = true
